export enum newsLetterType {
  NEWSLETTER = "NEWSLETTER",
  SUBSCRIBE = "SUBSCRIBE",
  UNSUBSCRIBE = "UNSUBSCRIBE",
  LOADING = "NEWSLETTER_LOADING",
  ERROR = "NEWSLETTER_ERROR",
  CLEAR_SUBS = "CLEAR_SUBS",
}
