export enum CartType {
  GET_CART = "GET_CART",
  ADD_CART = "ADD_CART",
  DELETE_CART = "DELETE_CART",
  DELETE_CART_ITEM = "DELETE_CART_ITEM",
  CLEAR_CART = "CLEAR_CART",
  ERROR = "CART_ERROR",
  LOADING = "CART_LOADING",
  CLEAR = "CART_CLEAR",
}
