export enum productType {
  GET_PRODUCTS = "GET_PRODUCTS",
  GET_PRODUCT = "GET_PRODUCT",
  LOADING = "LOADING",
  ERROR = "ERROR",
  CLEAR = "CLEAR_PRODUCTS",
  CREATE_PRODUCT = "CREATE_PRODUCT",
  UPDATE_PRODUCT = "UPDATE_PRODUCT",
  DELETE_PRODUCT = "DELETE_PRODUCT",
}
