export enum categoriesType {
  GET_CATEGORIES = "GET_CATEGORIES",
  GET_CATEGORY = "GET_CATEGORY",
  GET_SUB_CATEGORIES = "GET_SUB_CATEGORIES",
  LOADING = "CATEGORY_LOADING",
  ERROR = "CATEGORY_ERROR",
  CLEAR = "CLEAR_CATEGORIES",
}
