enum SellerTypes {
  SELLER_VERIFICATION = 'SELLER_VERIFICATION',
  START_SELLING = 'START_SELLING',
  GET_SELLER = 'GET_SELLER',
  SELLER_LOADING = 'SELLER_LOADING',
  SELLER_ERROR = 'SELLER_ERROR',
}

export default SellerTypes;
