export enum searchType {
  GET_SEARCH_OBJECTS = "GET_SEARCH_OBJECTS",
  LOADING = "SEARCH_LOADING",
  SEARCHED = "SEARCHED",
  ERROR = "SEARCH_ERROR",
  CLEAR = "CLEAR_SEARCH",
  SET_SEARCH_PAGE = "SET_SEARCH_PAGE",
}
