export enum WishlistType {
  GET_WISHLISTS = "GET_WISHLISTS",
  ADD_WISHLIST = "ADD_WISHLIST",
  CLEAR_WISHLIST = "CLEAR_WISHLIST",
  ERROR = "WISHLIST_ERROR",
  LOADING = "WISHLIST_LOADING",
  CLEAR = "WISHLIST_CLEAR",
}
